apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/Clustral/gitops.git
    path: platform/cloudflare-ddns
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    syncOptions:
      - CreateNamespace=true